projects:
  amplifyDatasource:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - taskmaster
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
